Update UG
AY2021S1-CS2103T-F13-2/tp pull request #175
Opened 2020-11-06 14:39 UTC by pennhanlee

UG Updated as per meeting except

* Trying out HTML <img> tag to resize the images to fit horizontally in a table

2020-11-06 15:47 UTC, angrybunny123 approved these changes
LGTM!

2020-11-06 16:04 UTC, pangpuncake requested changes
I think you are probably trying to link the picture example table to the example command but to me it feels disjointed like they are separate examples. Perhaps we can discuss this further?

2020-11-06 16:04 UTC, pangpuncake commented on docs/UserGuide.md
> +| <img src="images/deleteeg2.png" alt="delete" width="750px"> | <img src="images/deleteeg2.png" alt="delete" width="750px"> |
I think you used the wrong image for the first column?
In addition, perhaps it would be clearer to use Before `delete 2` and After `delete 2` to make it clearer to the users what is happening.

2020-11-06 16:04 UTC, pangpuncake commented on docs/UserGuide.md
> +| <img src="images/editeg1.png" alt="edit" width="750px"> | <img src="images/editeg2.png" alt="edit" width="750px"> |
Perhaps instead of "Before 2nd book is edited" you could specify the command used, so that the users know what is happening in the example. For example, "Before `edit 2 b/200`" etc

2020-11-06 16:04 UTC, pangpuncake commented on docs/UserGuide.md
> +| <img src="images/goaldeleg1.png" alt="goaldel" width="750px"> | <img src="images/goaldeleg2.png" alt="goaldel" width="750px"> |
Same thing here, perhaps you can use the example command.

2020-11-07 03:30 UTC, TanLeYang commented on docs/DeveloperGuide.md
> +to the User will be created by `XYZCommand` and returned to the user.
Instead of returned to the user, maybe use "passed to the Ui component to be displayed to the user"?

2020-11-07 03:30 UTC, TanLeYang commented on docs/DeveloperGuide.md
> +`XYZCommand` will then handle the specific action of the command and interact with the `ModelManager` to display the appropriate
I think we should mention the execute method here, maybe something like "`XYZCommand` will perform the functionality of the command in the `Command#execute()` method, interacting with and modifying the `ModelManager` appropriately."

2020-11-07 15:17 UTC, merged